# Render Infrastructure as Code Blueprint
# This file automatically tells Render how to deploy our FastAPI Container
services:
  - type: web
    name: polyglot-fastapi
    env: docker
    region: ohio
    plan: free
    branch: main
    # Point Render to our backend directory to build the Dockerfile
    dockerContext: ./backends/fastapi
    dockerfilePath: ./backends/fastapi/Dockerfile
    # Automatically deploy when code is pushed to main
    autoDeploy: true
    # Connects to the Render Environment Group named 'SUPABASE_CREDENTIALS'
    envVars:
      - fromGroup: SUPABASE_CREDENTIALS
